name: Test

on:
  pull_request

jobs:
  test:
    runs-on: macos-latest

    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true

    steps:
      - uses: actions/checkout@v2

      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '13.3'

      - name: execute tests
        run: xcodebuild -scheme iOSEngineerCodeCheck -sdk iphonesimulator -destination platform='iOS Simulator,name=iPhone 13,OS=15.2' test
